#pragma once

#include <Windows.h>

#define IO_GET_CLIENTADDRESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x727, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTLCUSTOM CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

typedef struct _MOUSEDATA
{
	LONG XMOVE;
	LONG YMOVE;
	LONG LDOWN;
} MOUSEDATA, * PMOUSEDATA;